### PR TITLE
Enhance the About-Us section #5

### PR DESCRIPTION
**Pull request by Saumya008**
about_us

### CODE REVIEW

**Comment by saumilyagupta** [comment]
Sister you've done awesome commit but now we have to change other sections in this very color scheme

**Comment by saumilyagupta** [comment]
i'm ready to accept your pull request but send me other sections changed in same manner.

**Comment by Saumya008** [comment]
Ok sure, so can i make separate pull requests for rest of the sections.

**Comment by cpjudgesarchive** [comment]
@Saumya008  are you a college student.

**Pull request closed without merging**
